apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: default # Replace with your namespace if needed
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  PGDATA: /var/lib/postgresql/data/pgdata
