apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: ns-32  # Specify the namespace
  labels:
    app: postgres
data:
  POSTGRES_DB: db
  POSTGRES_USER: root
  POSTGRES_PASSWORD: 123
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: ns-32  # Specify the namespace
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi  # Changed to 100 Mi (100 MB)
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: ns-32  # Specify the namespace
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi  # Changed to 100 Mi (100 MB)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ns-32  # Specify the namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:17'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-conf
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ns-32  # Specify the namespace
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
